{% set name = "geodemo" %}
{% set version = "0.0.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e7e430f9809057da197a7b0dbfd9e9ac2c3d869adf3f59e64c35d734bdf83156

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - earthengine-api
    - folium
    - ipyleaflet
    - pyshp
    - python >=3.6

test:
  imports:
    - geodemo

about:
  home: "https://github.com/giswqs/geodemo"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Python package for interactive mapping"
  doc_url: https://geodemo.gishub.org
  dev_url: https://github.com/giswqs/geodemo

extra:
  recipe-maintainers:
    - giswqs
